grid_map_topic: /vmap_og/grid_map
grid_map_visualizations:
  - name: original
    type: occupancy_grid
    params:
     layer: original
     data_min: 0
     data_max: 100
  - name: wayarea
    type: occupancy_grid
    params:
     layer: wayarea
     data_min: 0
     data_max: 100
  - name: points_wayarea
    type: occupancy_grid
    params:
     layer: points_wayarea
     data_min: 0
     data_max: 100
